package com.gfan.game.promotion.dao;

import java.util.List;

import com.gfan.game.promotion.entity.po.GameDataPo;
import com.gfan.game.promotion.entity.po.GameDataPoExample;

public interface GameDataPoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	int countByExample(GameDataPoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	int insert(GameDataPo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	int insertSelective(GameDataPo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	List<GameDataPo> selectByExample(GameDataPoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	GameDataPo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(GameDataPo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	int updateByPrimaryKey(GameDataPo record);
}