package com.gfan.game.promotion.entity.po;

import java.io.Serializable;
import java.util.Date;

public class ChannelPO implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column game_data_channel_xiaomi.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column game_data_channel_xiaomi.channel_id
	 * @mbggenerated
	 */
	private String channelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column game_data_channel_xiaomi.channel_level
	 * @mbggenerated
	 */
	private Byte channelLevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column game_data_channel_xiaomi.description
	 * @mbggenerated
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column game_data_channel_xiaomi.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table game_data_channel_xiaomi
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column game_data_channel_xiaomi.id
	 * @return  the value of game_data_channel_xiaomi.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column game_data_channel_xiaomi.id
	 * @param id  the value for game_data_channel_xiaomi.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column game_data_channel_xiaomi.channel_id
	 * @return  the value of game_data_channel_xiaomi.channel_id
	 * @mbggenerated
	 */
	public String getChannelId() {
		return channelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column game_data_channel_xiaomi.channel_id
	 * @param channelId  the value for game_data_channel_xiaomi.channel_id
	 * @mbggenerated
	 */
	public void setChannelId(String channelId) {
		this.channelId = channelId == null ? null : channelId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column game_data_channel_xiaomi.channel_level
	 * @return  the value of game_data_channel_xiaomi.channel_level
	 * @mbggenerated
	 */
	public Byte getChannelLevel() {
		return channelLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column game_data_channel_xiaomi.channel_level
	 * @param channelLevel  the value for game_data_channel_xiaomi.channel_level
	 * @mbggenerated
	 */
	public void setChannelLevel(Byte channelLevel) {
		this.channelLevel = channelLevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column game_data_channel_xiaomi.description
	 * @return  the value of game_data_channel_xiaomi.description
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column game_data_channel_xiaomi.description
	 * @param description  the value for game_data_channel_xiaomi.description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description == null ? null : description.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column game_data_channel_xiaomi.create_time
	 * @return  the value of game_data_channel_xiaomi.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column game_data_channel_xiaomi.create_time
	 * @param createTime  the value for game_data_channel_xiaomi.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
}