package com.gfan.game.promotion.entity.po;

import java.util.ArrayList;
import java.util.List;
import java.util.Date;

public class GameDataPoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	public GameDataPoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andAppidIsNull() {
			addCriterion("appId is null");
			return (Criteria) this;
		}

		public Criteria andAppidIsNotNull() {
			addCriterion("appId is not null");
			return (Criteria) this;
		}

		public Criteria andAppidEqualTo(Integer value) {
			addCriterion("appId =", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidNotEqualTo(Integer value) {
			addCriterion("appId <>", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidGreaterThan(Integer value) {
			addCriterion("appId >", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidGreaterThanOrEqualTo(Integer value) {
			addCriterion("appId >=", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidLessThan(Integer value) {
			addCriterion("appId <", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidLessThanOrEqualTo(Integer value) {
			addCriterion("appId <=", value, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidIn(List<Integer> values) {
			addCriterion("appId in", values, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidNotIn(List<Integer> values) {
			addCriterion("appId not in", values, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidBetween(Integer value1, Integer value2) {
			addCriterion("appId between", value1, value2, "appid");
			return (Criteria) this;
		}

		public Criteria andAppidNotBetween(Integer value1, Integer value2) {
			addCriterion("appId not between", value1, value2, "appid");
			return (Criteria) this;
		}

		public Criteria andGameNameIsNull() {
			addCriterion("game_name is null");
			return (Criteria) this;
		}

		public Criteria andGameNameIsNotNull() {
			addCriterion("game_name is not null");
			return (Criteria) this;
		}

		public Criteria andGameNameEqualTo(String value) {
			addCriterion("game_name =", value, "gameName");
			return (Criteria) this;
		}

		public Criteria andGameNameNotEqualTo(String value) {
			addCriterion("game_name <>", value, "gameName");
			return (Criteria) this;
		}

		public Criteria andGameNameGreaterThan(String value) {
			addCriterion("game_name >", value, "gameName");
			return (Criteria) this;
		}

		public Criteria andGameNameGreaterThanOrEqualTo(String value) {
			addCriterion("game_name >=", value, "gameName");
			return (Criteria) this;
		}

		public Criteria andGameNameLessThan(String value) {
			addCriterion("game_name <", value, "gameName");
			return (Criteria) this;
		}

		public Criteria andGameNameLessThanOrEqualTo(String value) {
			addCriterion("game_name <=", value, "gameName");
			return (Criteria) this;
		}

		public Criteria andGameNameLike(String value) {
			addCriterion("game_name like", value, "gameName");
			return (Criteria) this;
		}

		public Criteria andGameNameNotLike(String value) {
			addCriterion("game_name not like", value, "gameName");
			return (Criteria) this;
		}

		public Criteria andGameNameIn(List<String> values) {
			addCriterion("game_name in", values, "gameName");
			return (Criteria) this;
		}

		public Criteria andGameNameNotIn(List<String> values) {
			addCriterion("game_name not in", values, "gameName");
			return (Criteria) this;
		}

		public Criteria andGameNameBetween(String value1, String value2) {
			addCriterion("game_name between", value1, value2, "gameName");
			return (Criteria) this;
		}

		public Criteria andGameNameNotBetween(String value1, String value2) {
			addCriterion("game_name not between", value1, value2, "gameName");
			return (Criteria) this;
		}

		public Criteria andClassNameIsNull() {
			addCriterion("class_name is null");
			return (Criteria) this;
		}

		public Criteria andClassNameIsNotNull() {
			addCriterion("class_name is not null");
			return (Criteria) this;
		}

		public Criteria andClassNameEqualTo(String value) {
			addCriterion("class_name =", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameNotEqualTo(String value) {
			addCriterion("class_name <>", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameGreaterThan(String value) {
			addCriterion("class_name >", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameGreaterThanOrEqualTo(String value) {
			addCriterion("class_name >=", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameLessThan(String value) {
			addCriterion("class_name <", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameLessThanOrEqualTo(String value) {
			addCriterion("class_name <=", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameLike(String value) {
			addCriterion("class_name like", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameNotLike(String value) {
			addCriterion("class_name not like", value, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameIn(List<String> values) {
			addCriterion("class_name in", values, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameNotIn(List<String> values) {
			addCriterion("class_name not in", values, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameBetween(String value1, String value2) {
			addCriterion("class_name between", value1, value2, "className");
			return (Criteria) this;
		}

		public Criteria andClassNameNotBetween(String value1, String value2) {
			addCriterion("class_name not between", value1, value2, "className");
			return (Criteria) this;
		}

		public Criteria andIconUrlIsNull() {
			addCriterion("icon_url is null");
			return (Criteria) this;
		}

		public Criteria andIconUrlIsNotNull() {
			addCriterion("icon_url is not null");
			return (Criteria) this;
		}

		public Criteria andIconUrlEqualTo(String value) {
			addCriterion("icon_url =", value, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlNotEqualTo(String value) {
			addCriterion("icon_url <>", value, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlGreaterThan(String value) {
			addCriterion("icon_url >", value, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlGreaterThanOrEqualTo(String value) {
			addCriterion("icon_url >=", value, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlLessThan(String value) {
			addCriterion("icon_url <", value, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlLessThanOrEqualTo(String value) {
			addCriterion("icon_url <=", value, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlLike(String value) {
			addCriterion("icon_url like", value, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlNotLike(String value) {
			addCriterion("icon_url not like", value, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlIn(List<String> values) {
			addCriterion("icon_url in", values, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlNotIn(List<String> values) {
			addCriterion("icon_url not in", values, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlBetween(String value1, String value2) {
			addCriterion("icon_url between", value1, value2, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andIconUrlNotBetween(String value1, String value2) {
			addCriterion("icon_url not between", value1, value2, "iconUrl");
			return (Criteria) this;
		}

		public Criteria andApkUrlIsNull() {
			addCriterion("apk_url is null");
			return (Criteria) this;
		}

		public Criteria andApkUrlIsNotNull() {
			addCriterion("apk_url is not null");
			return (Criteria) this;
		}

		public Criteria andApkUrlEqualTo(String value) {
			addCriterion("apk_url =", value, "apkUrl");
			return (Criteria) this;
		}

		public Criteria andApkUrlNotEqualTo(String value) {
			addCriterion("apk_url <>", value, "apkUrl");
			return (Criteria) this;
		}

		public Criteria andApkUrlGreaterThan(String value) {
			addCriterion("apk_url >", value, "apkUrl");
			return (Criteria) this;
		}

		public Criteria andApkUrlGreaterThanOrEqualTo(String value) {
			addCriterion("apk_url >=", value, "apkUrl");
			return (Criteria) this;
		}

		public Criteria andApkUrlLessThan(String value) {
			addCriterion("apk_url <", value, "apkUrl");
			return (Criteria) this;
		}

		public Criteria andApkUrlLessThanOrEqualTo(String value) {
			addCriterion("apk_url <=", value, "apkUrl");
			return (Criteria) this;
		}

		public Criteria andApkUrlLike(String value) {
			addCriterion("apk_url like", value, "apkUrl");
			return (Criteria) this;
		}

		public Criteria andApkUrlNotLike(String value) {
			addCriterion("apk_url not like", value, "apkUrl");
			return (Criteria) this;
		}

		public Criteria andApkUrlIn(List<String> values) {
			addCriterion("apk_url in", values, "apkUrl");
			return (Criteria) this;
		}

		public Criteria andApkUrlNotIn(List<String> values) {
			addCriterion("apk_url not in", values, "apkUrl");
			return (Criteria) this;
		}

		public Criteria andApkUrlBetween(String value1, String value2) {
			addCriterion("apk_url between", value1, value2, "apkUrl");
			return (Criteria) this;
		}

		public Criteria andApkUrlNotBetween(String value1, String value2) {
			addCriterion("apk_url not between", value1, value2, "apkUrl");
			return (Criteria) this;
		}

		public Criteria andApksizeIsNull() {
			addCriterion("apkSize is null");
			return (Criteria) this;
		}

		public Criteria andApksizeIsNotNull() {
			addCriterion("apkSize is not null");
			return (Criteria) this;
		}

		public Criteria andApksizeEqualTo(Float value) {
			addCriterion("apkSize =", value, "apksize");
			return (Criteria) this;
		}

		public Criteria andApksizeNotEqualTo(Float value) {
			addCriterion("apkSize <>", value, "apksize");
			return (Criteria) this;
		}

		public Criteria andApksizeGreaterThan(Float value) {
			addCriterion("apkSize >", value, "apksize");
			return (Criteria) this;
		}

		public Criteria andApksizeGreaterThanOrEqualTo(Float value) {
			addCriterion("apkSize >=", value, "apksize");
			return (Criteria) this;
		}

		public Criteria andApksizeLessThan(Float value) {
			addCriterion("apkSize <", value, "apksize");
			return (Criteria) this;
		}

		public Criteria andApksizeLessThanOrEqualTo(Float value) {
			addCriterion("apkSize <=", value, "apksize");
			return (Criteria) this;
		}

		public Criteria andApksizeIn(List<Float> values) {
			addCriterion("apkSize in", values, "apksize");
			return (Criteria) this;
		}

		public Criteria andApksizeNotIn(List<Float> values) {
			addCriterion("apkSize not in", values, "apksize");
			return (Criteria) this;
		}

		public Criteria andApksizeBetween(Float value1, Float value2) {
			addCriterion("apkSize between", value1, value2, "apksize");
			return (Criteria) this;
		}

		public Criteria andApksizeNotBetween(Float value1, Float value2) {
			addCriterion("apkSize not between", value1, value2, "apksize");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table game_data_xiaomi
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table game_data_xiaomi
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andGameNameLikeInsensitive(String value) {
            addCriterion("upper(game_name) like", value.toUpperCase(), "gameName");
            return this;
        }

        public Criteria andClassNameLikeInsensitive(String value) {
            addCriterion("upper(class_name) like", value.toUpperCase(), "className");
            return this;
        }

        public Criteria andIconUrlLikeInsensitive(String value) {
            addCriterion("upper(icon_url) like", value.toUpperCase(), "iconUrl");
            return this;
        }

        public Criteria andApkUrlLikeInsensitive(String value) {
            addCriterion("upper(apk_url) like", value.toUpperCase(), "apkUrl");
            return this;
        }
    }
}